title: "Fritz Bayer"
author: "Fritz Bayer"
description: <a href="https://ethz.ch/en.html">ETH Zürich</a>
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

url: 'https://fritzbayer.github.io/' # your main domain
baseurl: '' # if you're using custom domain keep this blank example: baseurl: ''

# Layout

show_social: true         # show footer
show_excerpts: false       # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "publications.md"}
  - {file: "software.md"}
  - {file: "talks.md"}
#  - {file: "tools.md"}
  - {file: "index.md"}
  - {file: "contact.md"}
#  - {file: "README.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
#  - {title: Mail, icon: envelope, url: "mailto:frbayer at ethz.ch"}
  - {title: Github, icon: github, url: "https://github.com/fritzbayer"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/fritz-bayer/"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/BayesianBayer"} 
  - {title: Google, icon: graduation-cap, url: "https://scholar.google.com/citations?user=2TwrSx4AAAAJ&hl=en"} 
#  - {title: Scholar, icon: scholar, url: "https://scholar.google.com/citations?user=2TwrSx4AAAAJ&hl=en"}
#  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

# Google Analytics
google_analytics: UA-218088840-1

remote_theme: niklasbuschmann/contrast@v2.11

plugins:
 - jekyll-remote-theme
 - jekyll-feed
 - jekyll-seo-tag
